version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: camana_homes_db
    environment:
      POSTGRES_DB: camana_homes
      POSTGRES_USER: camana_user
      POSTGRES_PASSWORD: camana_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U camana_user -d camana_homes"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
